# Generated by Django 4.1.4 on 2022-12-24 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 24, 22, 27, 31, 319094)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 24, 22, 27, 31, 319094)),
        ),
    ]
